version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./mentorsphere-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend